### ISSUE TITLE
get rid of get and post in in urls as much as possible 

### ISSUE THREAD

**Issue by nadunindunil** [LetsBuildSomething/video-portal-backend#2]
- user/getAll should be user/all or something similar
- create and /user like in built URLs should omit for security measures

**Comment by ShanikaEdiriweera** [comment]
1) Regarding - "user/getAll should be user/all or something similar"
 // user routes
  'GET /user/:user_id': 'UserController.getUser',
  'GET /user': 'UserController.getUsers', 
  'POST /user': 'UserController.createUser',
  'POST /user/:user_id': 'UserController.editUser',
  'DELETE /user/:user_id': 'UserController.deleteUser',

  // role endpoints
  'GET /role': 'RoleController.getRoles', 
  'POST /role': 'RoleController.createRole',
  'DELETE /role/:role_id': 'RoleController.deleteRole',
  'POST /role/:role_id/add_playlists': 'RoleController.addPlaylists',
  'POST /role/:role_id/remove_playlists': 'RoleController.removePlaylists',

  // video routes
   'GET /video/:video_id/users_who_can_answer_comments': 'VideoController.getUsersWhoCanAnswerComments',

  // playlist routes
  'GET /playlist/:playlist_id/users_who_can_answer_comments': 'PlaylistController.getUsersWhoCanAnswerComments',

Above are the endpoints I created. 
There are no such 'get..' endpoints.

**Comment by ShanikaEdiriweera** [comment]
2) Regarding - "create and /user like in built URLs should omit for security measures"
Could you please explain more. I did not get the idea.

**Comment by janakact** [comment]
Don't open foolish issues.
